AWSTemplateFormatVersion: '2010-09-09'
Description: This will spin up an EC2 instance - this will be the EC2 From the Github Directly.

Resources: 
  myEC2Instance: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      InstanceType: 't2.micro'
      ImageId: 'ami-0912f71e06545ad88'
      Tags:
        - Key: Name
          Value: MyEC2Instance
        - Key: Environment
          Value: Dev
        - Key: Project
          Value: CloudFormationDemo
